image: docker:dind
stages:
  - build
  - deploy

build_dev:
  stage: build
  script:
    - docker build -t ecotrans_backend_dev:$CI_COMMIT_SHORT_SHA -f DockerfileDev .
    - docker login --username $HARBOR_USERNAME --password $HARBOR_PASSWORD $HARBOR_HOST
    - docker tag ecotrans_backend_dev:$CI_COMMIT_SHORT_SHA $HARBOR_HOST/ecotrans_backend/ecotrans_backend_dev:$CI_COMMIT_SHORT_SHA
    - docker push $HARBOR_HOST/ecotrans_backend/ecotrans_backend_dev:$CI_COMMIT_SHORT_SHA
  only:
    - dev

deploy_dev:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Starting to deploy"
    - chmod og= $SSH_PRIVATE_KEY_DEV
    - apk update && apk add openssh-client
    - ssh -i $SSH_PRIVATE_KEY_DEV -o StrictHostKeyChecking=no $SERVER_USER_DEV@$SERVER_IP_DEV "docker login --username $HARBOR_USERNAME --password $HARBOR_PASSWORD $HARBOR_HOST"
    - ssh -i $SSH_PRIVATE_KEY_DEV -o StrictHostKeyChecking=no $SERVER_USER_DEV@$SERVER_IP_DEV "docker pull $HARBOR_HOST/ecotrans_backend/ecotrans_backend_dev:$CI_COMMIT_SHORT_SHA"
    - ssh -i $SSH_PRIVATE_KEY_DEV -o StrictHostKeyChecking=no $SERVER_USER_DEV@$SERVER_IP_DEV "docker compose --file /home/deploy/Eecotrans/BackEnd/ex_backend/docker-compose.yml down"
    - |
      ssh -i $SSH_PRIVATE_KEY_DEV -o StrictHostKeyChecking=no $SERVER_USER_DEV@$SERVER_IP_DEV '
        sed -i "s|image: harbor.mypartner-isc.com/ecotrans_backend/ecotrans_backend_dev:[^[:space:]]*|image: harbor.mypartner-isc.com/ecotrans_backend/ecotrans_backend_dev:'"$CI_COMMIT_SHORT_SHA"'|g" /home/deploy/Eecotrans/BackEnd/ex_backend/docker-compose.yml
      '
    - ssh -i $SSH_PRIVATE_KEY_DEV -o StrictHostKeyChecking=no $SERVER_USER_DEV@$SERVER_IP_DEV "docker compose --file /home/deploy/Eecotrans/BackEnd/ex_backend/docker-compose.yml up -d"
  environment:
    name: dev
  only:
    - dev

build_staging:
  stage: build
  script:
    - docker build -t ecotrans_backend_stg:$CI_COMMIT_SHORT_SHA -f DockerfileStg .
    - docker login --username $HARBOR_USERNAME --password $HARBOR_PASSWORD $HARBOR_HOST
    - docker tag ecotrans_backend_stg:$CI_COMMIT_SHORT_SHA $HARBOR_HOST/ecotrans_backend/ecotrans_backend_stg:$CI_COMMIT_SHORT_SHA
    - docker push $HARBOR_HOST/ecotrans_backend/ecotrans_backend_stg:$CI_COMMIT_SHORT_SHA
  only:
    - staging

deploy_stg:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Starting to deploy"
    - chmod og= $SSH_PRIVATE_KEY_STAGING
    - apk update && apk add openssh-client
    - ssh -i $SSH_PRIVATE_KEY_STAGING -o StrictHostKeyChecking=no $SERVER_USER_STAGING@$SERVER_IP_STAGING "docker login --username $HARBOR_USERNAME --password $HARBOR_PASSWORD $HARBOR_HOST"
    - ssh -i $SSH_PRIVATE_KEY_STAGING -o StrictHostKeyChecking=no $SERVER_USER_STAGING@$SERVER_IP_STAGING "docker pull $HARBOR_HOST/ecotrans_backend/ecotrans_backend_stg:$CI_COMMIT_SHORT_SHA"
    - |
      ssh -i $SSH_PRIVATE_KEY_STAGING -o StrictHostKeyChecking=no $SERVER_USER_STAGING@$SERVER_IP_STAGING '
        sed -i "s|image: harbor.mypartner-isc.com/ecotrans_backend/ecotrans_backend_stg:[^[:space:]]*|image: harbor.mypartner-isc.com/ecotrans_backend/ecotrans_backend_stg:'"$CI_COMMIT_SHORT_SHA"'|g" /home/mypartner/Xchange/ecotrans_backend/ecotrans_backend.yaml
      '
    - ssh -i $SSH_PRIVATE_KEY_STAGING -o StrictHostKeyChecking=no $SERVER_USER_STAGING@$SERVER_IP_STAGING "kubectl apply -f /home/mypartner/Xchange/ecotrans_backend/ecotrans_backend.yaml"
  environment:
    name: staging
  only:
    - staging
